---
resources:
- name: git-sample-app
  type: git
  source:
    uri: https://github.com/E458567/spring-petclinic.git
    branch: master

- name: git-quality-pipeline
  type: git
  source:
    uri: https://github.com/E458567/quality-pipeline.git 
    branch: master

jobs:
- name: sonar-scan
  plan:
  - get: git-sample-app
  - get: git-quality-pipeline
  - task: compile and unit tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: myautopoc/8-jdk-alpine-git
      inputs:
        - name: git-sample-app
        - name: git-quality-pipeline
      outputs:
        - name: updated-sample-app
      run:
        path: git-quality-pipeline/scripts/mvn-build.sh

  - task: sonar scan
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: myautopoc/8-jdk-alpine-git
      inputs:
        - name: updated-sample-app
        - name: git-quality-pipeline
      run:
        path: git-quality-pipeline/scripts/mvn-sonar.sh

