---
resources:
- name: git-sample-app
  type: git
  source:
    uri: https://github.com/E458567/spring-petclinic.git
    branch: master

jobs:
- name: compile
  plan:
  - get: git-sample-app
  - get: git-quality-pipeline
  - task: compile source and tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: myautopoc/8-jdk-alpine-git
      inputs:
        - name: git-sample-app
        - name: git-quality-pipeline
      outputs:
        - name: updated-sample-app
      run:
        path: ./git-quality-pipeline/scripts/mvn-compile.sh

  - put: sample-app-image
    params:
      build: updated-sample-app

- name: unit-test
  plan:
  - get: sample-app-image
    passed: [compile]
    trigger: true
  - get: git-quality-pipeline
  - task: run JUnit tests
    image: sample-app-image
    file: git-quality-pipeline/tasks/task-mvn-test.yml
